version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      target: production # Use the production stage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      target: production # Use the production stage
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
